#Makefile 1

#This is a comment section \
It is a simple construct of makefile for the compilation of these files.\
Uncomment the below section for compilation


#all:
#	#gcc main.c misc.c -o main
#
#


#Makefile 2


#make file - this is a comment section
#setting the target
#
#CC=gcc    #compiler
#TARGET=omega     #Target file name
#
#
#all: 
#	$(CC) main.c misc.c -o $(TARGET)
#
#clean:
#	rm $(TARGET)
#



#Makefile 3
#make file -this is a comment section

CC=gcc #compiler
TARGET=hello       #target file name


all:	main.o misc.o
	$(CC) main.c misc.c -o $(TARGET)

clean:
	rm *.o $(TARGET)
